<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassroomBooking.Contracts\ClassroomBooking.Contracts.csproj" />
    <ProjectReference Include="..\ClassroomBooking.Bookings\ClassroomBooking.Bookings.csproj" />
    <ProjectReference Include="..\ClassroomBooking.Schedule\ClassroomBooking.Schedule.csproj" />
    <ProjectReference Include="..\ClassroomBooking.Classrooms\ClassroomBooking.Classrooms.csproj" />
    <ProjectReference Include="..\ClassroomBooking.Users\ClassroomBooking.Users.csproj" />
  </ItemGroup>

</Project>
